name: "Multi event pipeline / workflow"  # Name of the pipeline

on:
    push:   # Event: Whenever a push is made to the repository on the master/test branch
        branches:
            - master
            - test
    pull_request:  # Event: Whenever a pull request is opened on the repository
        branches:
            - master
    workflow_dispatch: # Event: Manually trigger the workflow

jobs:
    on-push:   # Job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:  # Steps to be executed in the job
            - name: "Running on master/test branch"  # Step 1
              run: echo "Running on master/test branch"

    on-pull-request: # Job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:  # Steps to be executed in the job
            - name: "Running on pull request"  # Step 2
              run: echo "Running on pull request"

    on-workflow-dispatch: # Job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:  # Steps to be executed in the job
            - name: "Running on workflow dispatch"  # Step 3
              run: echo "Running on workflow dispatch"